name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: nhkwardana30/githuactioncicd-service-backend-1
  REGISTRY: docker.io

jobs:
  deploy-staging:
    if: github.event_name == 'push'
    runs-on: [self-hosted, linux]
    environment: staging

    steps:
      - name: Deploy to STAGING
        run: echo "Deploying to STAGING..."

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: [self-hosted, linux]
    environment: production

    steps:
      - name: Deploy to PRODUCTION
        run: echo "Deploying to PRODUCTION..."
